# Site settings
author: LaShanni Butler
title: Flatiron Data Science Blog post
header-img: img/home-bg.png
email: lashanni@gmail.com
copyright_name: LaShanni Butler
description: > # this means to ignore newlines until "baseurl:"
  Required Blogs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Sugaboo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
